# Generated by Django 4.2.5 on 2023-09-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
    ]
